---
title: "Gene_linear_modelling"
output: odf_document
---

```{r Import Libraries, include=FALSE}
library("limma")
library("ggplot2")
library("WGCNA")
options(stringsAsFactors = FALSE);
```

```{r Load Data, include=TRUE}
load("./filtered_TMT_Summary_Data.RData")
```

```{r Additive Linear Model, include=TRUE}
nCols <- ncol(filtered_TMT_Summary_Data)
nGenes <- nrow(filtered_TMT_Summary_Data)

# additive linear model
addBatchFactor <- c(2,2,1,1,3,3,4,4)
addDiseaseGroup <- factor(rep(addBatchFactor,5))
addDesign <- model.matrix(~addDiseaseGroup + 0)
colnames(addDesign) <- c("Ctl", "AD", "PD","ADPD")

addFit <- lmFit(filtered_TMT_Summary_Data[,7:nCols], addDesign)

contrast.matrix <- makeContrasts(AD-Ctl, PD-Ctl, ADPD-Ctl, levels=addDesign)
addFit2 <- contrasts.fit(addFit, contrast.matrix)
addFit2 <- eBayes(addFit2)
topGenesAdd <- topTable(addFit2, coef=1, adjust="BH")

# interaction linear model
Ctl <-factor(rep(c(0,0,1,1,0,0,0,0),5))
AD <- factor(rep(c(1,1,0,0,0,0,1,1),5))
PD <- factor(rep(c(0,0,0,0,1,1,1,1),5))
intDesign <- model.matrix(~Ctl + AD + PD + AD:PD + 0)
intDesign <- intDesign[,2:5]
colnames(intDesign) <- c("Ctl", "AD", "PD","ADPD")

intFit <- lmFit(filtered_TMT_Summary_Data[,7:nCols], intDesign)

contrast.matrix <- makeContrasts(AD-Ctl, PD-Ctl, ADPD-Ctl, levels=intDesign)
intFit2 <- contrasts.fit(intFit, contrast.matrix)
intFit2 <- eBayes(intFit2)
topGenesInt <- topTable(intFit2, coef=1, adjust="BH")
```



```{r Volcano plot, include=TRUE}
# Generate Log-fold changes
adAddGenes <- topTable(addFit2, coef=1, number=1000000, sort.by="logFC")
pdAddGenes <- topTable(addFit2, coef=2, number=1000000, sort.by="logFC")
adpdAddGenes <- topTable(addFit2, coef=3, number=1000000, sort.by="logFC")

adIntGenes <- topTable(intFit2, coef=1, number=1000000, sort.by="logFC")
pdIntGenes <- topTable(intFit2, coef=2, number=1000000, sort.by="logFC")
adpdIntGenes <- topTable(intFit2, coef=3, number=1000000, sort.by="logFC")

# Add compute expressed genes threshold (TRUE is differentially expressed)
adAddGenes$threshold = as.factor(abs(adAddGenes$logFC) > 0.25 & adAddGenes$P.Value < 0.05/nGenes)
pdAddGenes$threshold = as.factor(abs(pdAddGenes$logFC) > 0.25 & pdAddGenes$P.Value < 0.05/nGenes)
adpdAddGenes$threshold = as.factor(abs(adpdAddGenes$logFC) > 0.25 & adpdAddGenes$P.Value < 0.05/nGenes)

adIntGenes$threshold = as.factor(abs(adIntGenes$logFC) > 0.25 & adIntGenes$P.Value < 0.05/nGenes)
pdIntGenes$threshold = as.factor(abs(pdIntGenes$logFC) > 0.25 & pdIntGenes$P.Value < 0.05/nGenes)
adpdIntGenes$threshold = as.factor(abs(adpdIntGenes$logFC) > 0.25 & adpdIntGenes$P.Value < 0.05/nGenes)

# Generate volcano plots using the additive model.
g1 = ggplot(data=adAddGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Additive model: Ctrl vs. AD')
g1

g2 = ggplot(data=pdAddGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Additive model: Ctrl vs. PD')
g2

g3 = ggplot(data=adpdAddGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Additive model: Ctrl vs. ADPD')
g3

# Generate volcano plots using the interaction model.
g4 = ggplot(data=adIntGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Interaction model: Ctrl vs. AD')
g4

g5 = ggplot(data=pdIntGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Interaction model: Ctrl vs. PD')
g5

g6 = ggplot(data=adpdIntGenes, aes(x=logFC, y=-log10(P.Value), colour=threshold)) +
  geom_point(alpha=0.4, size=1.75) +
  theme(legend.position = "none") +
  xlim(c(-2.5, 2.5)) + ylim(c(0, 15)) +
  xlab("log2 fold change") + ylab("-log10 p-value") + ggtitle('Interaction model: Ctrl vs. ADPD')
g6
```

```{r}
# Get all differentially expressed genes into a dataframe


ad_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(adAddGenes[which(adAddGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(ad_ctl) <- ad_ctl[,1]
ad_ctl[,1] <- NULL
ad_ctl_data <- ad_ctl[,-1]
ad_ctl_data <- t(ad_ctl_data)

```



```{r}
gsg = goodSamplesGenes(ad_ctl_data, verbose = 3);
gsg$allOK


```



```{r}
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(ad_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")


```


```{r}

net = blockwiseModules(ad_ctl_data, power = 18,
TOMType = "unsigned", minModuleSize = 1,
reassignThreshold = 0, mergeCutHeight = 0.1,
numericLabels = TRUE, pamRespectsDendro = FALSE,
saveTOMs = TRUE,
saveTOMFileBase = "ad_ctl_tom",
verbose = 3)



```



```{r}

table(net$colors)

```

```{r}

# open a graphics window
sizeGrWindow(12, 9)
# Convert labels to colors for plotting
mergedColors = labels2colors(net$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(net$dendrograms[[1]], mergedColors[net$blockGenes[[1]]],
"Module colors",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)

```
```{r}
moduleLabels = net$colors
moduleColors = labels2colors(net$colors)
MEs = net$MEs;
geneTree = net$dendrograms[[1]];
save(MEs, moduleLabels, moduleColors, geneTree,
file = "FemaleLiver-02-networkConstruction-auto.RData")

```


```{r}

# Might have to do manual construction of blocks to get the maximally connected genes

get_max_conn_genes <- function(data, softPower, min_mod_size){
  softPower = softPower;
  adjacency = adjacency(data, power = softPower);
  
  # Turn adjacency into topological overlap
  TOM = TOMsimilarity(adjacency);
  dissTOM = 1-TOM
  
  # Call the hierarchical clustering function
  geneTree = hclust(as.dist(dissTOM), method = "average");
  # Plot the resulting clustering tree (dendrogram)
  sizeGrWindow(12,9)
  plot(geneTree, xlab="", sub="", main = "Gene clustering on TOM-based dissimilarity",
  labels = FALSE, hang = 0.04);
  
  minModuleSize = 1;
  # Module identification using dynamic tree cut:
  dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM,
  deepSplit = 2, pamRespectsDendro = FALSE,
  minClusterSize = min_mod_size);
  table(dynamicMods)
  
  # Convert numeric lables into colors
  dynamicColors = labels2colors(dynamicMods)
  table(dynamicColors)
  # Plot the dendrogram and colors underneath
  sizeGrWindow(8,6)
  plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
  dendroLabels = FALSE, hang = 0.03,
  addGuide = TRUE, guideHang = 0.05,
  main = "Gene dendrogram and module colors")
  
  
  # Maximally connected gene, let's call it mc_gene
  # For each cluster, find elements in that cluster, sum up the corresponding row from the     adjacency matrix.
  mc_genes = list()
  for(i in c(1:max(dynamicMods))){
    all_row_indices = which(dynamicMods == i)
    max_val = -1
    max_idx = -1
    for(id in all_row_indices){
      curr_sum = sum(adjacency[id,])
      if(curr_sum>max_val){
        max_val = curr_sum
        max_idx = id
      }
    }
    mc_genes[[i]] <- rownames(ad_ctl[max_idx,])
  }
  
  return(mc_genes)
}


```


# AD vs Ctrl, additive model
```{r}

# Get all differentially expressed genes into a dataframe


ad_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(adAddGenes[which(adAddGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(ad_ctl) <- ad_ctl[,1]
ad_ctl[,1] <- NULL
ad_ctl_data <- ad_ctl[,-1]
ad_ctl_data <- t(ad_ctl_data)

gsg = goodSamplesGenes(ad_ctl_data, verbose = 3);
gsg$allOK


# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(ad_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")


```
```{r}


mc_genes = get_max_conn_genes(ad_ctl_data, 18, 1)
unlist(mc_genes)

```


# PD vs Ctrl, additive model
```{r}
# Get all differentially expressed genes into a dataframe



pd_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(pdAddGenes[which(pdAddGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(pd_ctl) <- pd_ctl[,1]
pd_ctl[,1] <- NULL
pd_ctl_data <- pd_ctl[,-1]
pd_ctl_data <- t(pd_ctl_data)


#gsg = goodSamplesGenes(pd_ctl_data, verbose = 3);
#gsg$allOK


# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(pd_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")




```

```{r}

#Analyze all of them since fewer than 3 genes

rownames(pd_ctl)

```

# ADPD vs Ctrl, additive model
```{r}
# Get all differentially expressed genes into a dataframe



adpd_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(adpdAddGenes[which(adpdAddGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(adpd_ctl) <- adpd_ctl[,1]
adpd_ctl[,1] <- NULL
adpd_ctl_data <- adpd_ctl[,-1]
adpd_ctl_data <- t(adpd_ctl_data)


#gsg = goodSamplesGenes(pd_ctl_data, verbose = 3);
#gsg$allOK


# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(adpd_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")




```
```{r}
mc_genes = get_max_conn_genes(ad_ctl_data, 14, 1)
unlist(mc_genes)


```


# AD vs Ctrl, interaction model
```{r}


# Get all differentially expressed genes into a dataframe


ad_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(adIntGenes[which(adIntGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(ad_ctl) <- ad_ctl[,1]
ad_ctl[,1] <- NULL
ad_ctl_data <- ad_ctl[,-1]
ad_ctl_data <- t(ad_ctl_data)

gsg = goodSamplesGenes(ad_ctl_data, verbose = 3);
gsg$allOK


# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(ad_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")



```


```{r}

mc_genes = get_max_conn_genes(ad_ctl_data, 18, 1)
unlist(mc_genes)

```
# PD vs Ctrl
```{r}
# Same case, no differentially expressed genes

```

# ADPD vs Ctrl

```{r}
# Get all differentially expressed genes into a dataframe



adpd_ctl <-  as.data.frame((filtered_TMT_Summary_Data[as.integer(rownames(adpdIntGenes[which(adpdIntGenes$threshold == TRUE),])), c(1,2,7:nCols)]))

rownames(adpd_ctl) <- adpd_ctl[,1]
adpd_ctl[,1] <- NULL
adpd_ctl_data <- adpd_ctl[,-1]
adpd_ctl_data <- t(adpd_ctl_data)


gsg = goodSamplesGenes(adpd_ctl_data, verbose = 3);
gsg$allOK


# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(adpd_ctl_data, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.70,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")

```


```{r}

mc_genes = get_max_conn_genes(ad_ctl_data, 8, 1)
unlist(mc_genes)


```
